*-----------------------------------------------------------
* Title      : Practical 3, PART 1
* Written by : ISMAEL CHARAF MEGRINI
* Date       : 26/01/2026
* Description: 
*-----------------------------------------------------------
    ORG    $1000
START:                  

    LEA $4000, A1
    MOVE.B #100,(A1)


    SIMHALT             



    END    START        

*~Font name~Courier New~
*~Font size~10~
*~Tab type~1~
*~Tab size~4~
